### ISSUE TITLE
Get CUVPN working with Pi

### ISSUE THREAD

**Issue by r3cebarnett** [clemsonMakerspace/CATS#111]
This would allow us to talk to the SQL server on Wi-Fi.

**Comment by ophilli** [comment]
Perhaps the better issue is "Talk to SQL server over Wi-Fi". There are a lot of other ways to accomplish this, and several that I bet will be easier than the CUVPN.

**Comment by r3cebarnett** [comment]
I disagree. Unless we plan on deviating from Clemson's SQL service.

**Comment by ophilli** [comment]
Just one thought - open an SSH tunnel or VPN to a node on Ethernet. Would likely be much easier than CUVPN.

**Comment by r3cebarnett** [comment]
Wanna work on it? ;)

**Comment by ophilli** [comment]
Sure. On a wifi node run `ssh -L 9000:clemsonSQLURLHere:3306 user@makerspace` then in your Python change database host to localhost and port to 9000.

Done and done.

**Comment by ophilli** [comment]
I wanna make sure it's clear what I'm proposing really quick.

We've got a SQL database run by Clemson that we want to use - and there are a few things that we know:

1. CCIT says we have to be on ethernet to talk to the database
1. We MIGHT even need a whitelisted IP (CU Production SQL server requires one)
1. Nodes can be distributed over Eduroam or Ethernet
1. Nodes are most likely to get a DHCP address - not static
1. We have access to a server (makerspace) that is on ethernet and can possibly request static ip

Those are just the facts that I have available. CU VPN won't give us easily whitelistable IPs, and it may not count as ethernet, although we can easily test that. I'm also not sure how easy it is to setup from a CLI linux environment. I like the direction you're headed, but it might be worth exploring alternative options.

Here are just a few options:
1. CU VPN
1. SSH tunnel to a known ethernet server
1. VPN to a known ethernet server
1. Run a SQL proxy on a known ethernet server
1. Adjust program architecture so that nodes call an API on a known ethernet server that handles all SQL
1. Host our own SQL

**Comment by r3cebarnett** [comment]
Honestly I think option #5 is the easiest to adapt in a commercial setting as well as sake of ease but I don't want to break any laws relating to what we have on our own server.

**Comment by ophilli** [comment]
I'm doubtful we would be at risk for breaking any laws - but we would be responsible for managing our own data retention and recovery, which is substantially more work than one would expect.

**Comment by r3cebarnett** [comment]
Since we're using our own SQL server, this issue is resolved, yes?

**Comment by ophilli** [comment]
We are using our own SQL server for devel - but is this the production instance?

Once again, an issue I leave to the software team.

**Comment by r3cebarnett** [comment]
I think it is production instance. The only reason we couldn't use Clemson's service is because Clemson's way of accessing is lame.

**Comment by gacosta1** [comment]
@r3cebarnett I would agree with Maurice.

**Comment by r3cebarnett** [comment]
Executive decision made.
